-- ============================================================
-- NOVE STOR - Supabase Schema + Security Rules (RLS)
-- SQL Editor (SQL > New query) -> paste -> Run
-- ============================================================

-- ============ 1. TABLES ============

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  price numeric not null default 0,
  icon text default '📦',
  image text default '',
  category text default 'fivem',
  status text default 'active',
  features jsonb default '[]'::jsonb,
  link text default '',
  created_at timestamptz default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  label text not null,
  value text not null unique,
  color text default '#22d3ee',
  icon text default '📁'
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text default 'percent',           -- percent | fixed
  value numeric default 0,
  max_uses int default 0,
  used int default 0,
  active int default 1,
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_ref text not null,
  user_name text default '',
  email text default '',
  items jsonb default '[]'::jsonb,
  total numeric default 0,
  status text default 'completed',
  payment_id text default '',
  ip text default '',
  created_at timestamptz default now()
);

create table if not exists public.blocked_ips (
  id bigint generated by default as identity primary key,
  ip text not null,
  reason text default '',
  until timestamptz default null,
  created_at timestamptz default now()
);

create table if not exists public.security_logs (
  id bigint generated by default as identity primary key,
  type text default 'info',
  msg text default '',
  details text default '',
  ip text default '',
  user_email text default '',
  created_at timestamptz default now()
);

-- Admin profile: only the one row with role='owner' can change the store.
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null unique,
  role text default 'user',              -- user | admin | owner
  name text default '',
  device text default '',
  ip text default '',
  last_login_at timestamptz default now(),
  blocked int default 0,
  created_at timestamptz default now()
);

create table if not exists public.store_users (
  email text primary key,
  name text default '',
  device text default '',
  ip text default '',
  role text default 'user',
  is_admin int default 0,
  verified int default 0,
  avatar text default '',
  last_login_at timestamptz,
  joined_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.store_settings (
  id int primary key default 1,
  store_name text default 'NOVE STOR',
  logo text default 'images/logo.png',
  paypal text default '',
  social jsonb default '{}'::jsonb,
  emailjs jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

insert into public.store_settings (id, store_name) values (1, 'NOVE STOR')
  on conflict (id) do nothing;

-- Owner email (replace with your real admin email BEFORE running):
-- (use an email you actually own / can verify)
-- create table stores the FIRST verified user as owner via a trigger below.

-- ============ 2. SET THE OWNER ============
-- Run this ONCE with YOUR admin email:
-- update public.profiles set role = 'owner' where email = 'cr8381062@gmail.com';

-- ============ 3. ROW LEVEL SECURITY ============

alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.coupons enable row level security;
alter table public.orders enable row level security;
alter table public.blocked_ips enable row level security;
alter table public.security_logs enable row level security;
alter table public.profiles enable row level security;
alter table public.store_settings enable row level security;

-- --- store_users: customers may upsert their own public profile; any visitor may read
--     the public roster. Passwords/secret fields are NEVER uploaded (see publicUser). ---
drop policy if exists store_users_all on public.store_users;
create policy store_users_all on public.store_users for all using (true) with check (true);

-- --- products: everyone can read, only owner/admin modify ---
drop policy if exists products_read on public.products;
create policy products_read on public.products for select using (true);
drop policy if exists products_write on public.products;
create policy products_write on public.products for all using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
) with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);

-- --- categories: read public, write owner/admin ---
drop policy if exists categories_read on public.categories;
create policy categories_read on public.categories for select using (true);
drop policy if exists categories_write on public.categories;
create policy categories_write on public.categories for all using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
) with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);

-- --- coupons: HIDDEN from public (discount codes are secrets).
--     Only owner/admin can read or write. Checkout uses local coupons. ---
drop policy if exists coupons_read on public.coupons;
drop policy if exists coupons_read_owner on public.coupons;
create policy coupons_read_owner on public.coupons for select using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);
drop policy if exists coupons_write on public.coupons;
create policy coupons_write on public.coupons for all using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
) with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);

-- --- orders: anyone can insert a REAL checkout order (sanity-checked),
--     only owner/admin can read ---
drop policy if exists orders_insert on public.orders;
create policy orders_insert on public.orders for insert with check (
  coalesce(email,'') <> '' and total >= 0 and coalesce(payment_id,'') <> ''
);
drop policy if exists orders_read on public.orders;
create policy orders_read on public.orders for select using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);

-- --- blocked_ips: only owner/admin read/write ---
drop policy if exists blocked_ips_admin on public.blocked_ips;
create policy blocked_ips_admin on public.blocked_ips for all using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
) with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);

-- --- security_logs: owner/admin can write+read ---
drop policy if exists logs_admin on public.security_logs;
create policy logs_admin on public.security_logs for all using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
) with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);

-- --- profiles: user can read own, owner reads all; nobody writes their own role ---
drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select using (
  auth.uid() = id
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);
drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert with check (auth.uid() = id and role = 'user');
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update using (auth.uid() = id) with check (
  auth.uid() = id and role = 'user'
);
drop policy if exists profiles_update_admin on public.profiles;
create policy profiles_update_admin on public.profiles for update using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner' and p.blocked = 0)
) with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner' and p.blocked = 0)
);

-- --- store_settings: HIDDEN from public (may contain secrets).
--     Only owner/admin read; writes owner/admin. Logo/name come from browser. ---
drop policy if exists settings_read on public.store_settings;
drop policy if exists settings_read_owner on public.store_settings;
create policy settings_read_owner on public.store_settings for select using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);
drop policy if exists settings_write on public.store_settings;
create policy settings_write on public.store_settings for all using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
) with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0)
);

-- ============ 4. AUTO-CREATE PROFILE ON SIGNUP ============
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'name', 'User'));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============ 5. RPC: REAL KICK ============
-- Blocklist a client by IP (owner/admin only). The app checks this table server-side.
create or replace function public.block_ip(ip_text text, reason_text text default 'tampering', minutes int default 1440)
returns void language plpgsql security definer set search_path = public as $$
begin
  if exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0
  ) then
    insert into public.blocked_ips (ip, reason, until)
    values (ip_text, reason_text, now() + make_interval(mins => minutes));
  end if;
end;
$$;

-- Unblock
create or replace function public.unblock_ip(ip_text text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('owner','admin') and p.blocked = 0
  ) then
    delete from public.blocked_ips where ip = ip_text;
  end if;
end;
$$;

-- Is caller blocked right now? Called on boot by the store to self-protect.
create or replace function public.is_ip_blocked(ip_text text)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  return exists (
    select 1 from public.blocked_ips b
    where b.ip = ip_text and (b.until is null or b.until > now())
  );
end;
$$;